[env]
# can be defined as kcov, tarpaulin, ...
CARGO_MAKE_COVERAGE_PROVIDER = "tarpaulin"


[tasks.default]
alias = "test"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.tarpaulin]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "-v", "--fail-under=100"]

[tasks.coverage]
alias = "tarpaulin"

[tasks.github-push]
command = "git"
args = ["push", "-u", "origin", "HEAD"]

[tasks.github-create-pr]
command = "gh"
args = ["pr", "create", "--fill"]

[tasks.github-merge-pr]
command = "gh"
args = ["pr", "merge", "--merge", "--delete-branch"]
