[tasks.default]
alias = "test"

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.coverage]
install_crate = "cargo-tarpaulin"
command = "cargo"
args = ["tarpaulin", "-v", "--fail-under=100"]
